In [1]:
!pip install kaggle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!mkdir ~/.kaggle

In [4]:
!cp /content/drive/MyDrive/kaggle_api_credentials/kaggle.json ~/.kaggle/

In [5]:
!chmod 600 ~/.kaggle/kaggle.json

In [6]:
!kaggle datasets download vgs777/financial-label-sentiment-analysis-banking-app

  0% 0.00/18.2k [00:00<?, ?B/s]
100% 18.2k/18.2k [00:00<00:00, 39.9MB/s]


In [7]:
!unzip /content/financial-label-sentiment-analysis-banking-app.zip

Archive:  /content/financial-label-sentiment-analysis-banking-app.zip
  inflating: final_bfsi_lablel.csv   


In [10]:
!pip3 install -q -U bitsandbytes==0.42.0
!pip3 install -q -U accelerate==0.27.1
!pip3 install -q -U datasets==2.17.0
!pip3 install -q -U transformers==4.38.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 MB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.7/279.7 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 65.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 103.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━

In [ ]:
!pip3 install -q -U peft==0.8.2
!pip3 install -q -U trl==0.7.10

# Dataset Creation

In [8]:
import pandas as pd
df = pd.read_csv('final_bfsi_lablel.csv')

In [9]:
df

Financial_context  annotation_id  annotator  \
0           Financial             14          1   
1       Non Financial             15          1   
2       Non Financial             16          1   
3       Non Financial             17          1   
4       Non Financial             18          1   
..                ...            ...        ...   
383     Non Financial            382          1   
384         Financial            383          1   
385     Non Financial            370          1   
386         Financial            384          1   
387         Financial            399          1   

                                               content  \
0                  1] Customer service is really nice.   
1    2] It is not very easy to set up mobile bankin...   
2     I understand it's for safety but still a hassle.   
3                        3] App itself is easy to use.   
4    4] Unfortunately, you can't view your card num...   
..                                                 ...   
383                I don't know what's is the problem?   
384                           It's very disappointing.   
385  2nd largest bank in India but mobile app is no...   
386                                       What a pity.   
387                                           Perfect!   

                      created_at    id language  lead_time  score sentiment  \
0    2024-03-31T06:58:47.318794Z  1332       en      9.348      3  Positive   
1    2024-03-31T06:59:03.859506Z  1333       en     12.568      3   Neutral   
2    2024-03-31T06:59:46.583294Z  1334       en     21.842      3   Neutral   
3    2024-03-31T06:59:58.593876Z  1335       en      7.949      3  Positive   
4    2024-03-31T07:00:26.848093Z  1336       en     16.955      3  Negative   
..                           ...   ...      ...        ...    ...       ...   
383  2024-03-31T11:39:35.667314Z  2532       en      9.276      4  Negative   
384  2024-03-31T11:39:43.659762Z  2533       en      6.336      4  Negative   
385  2024-03-31T11:29:04.279001Z  2534       en      4.080      4  Negative   
386  2024-03-31T11:40:03.224609Z  2535       en     25.356      4  Negative   
387  2024-03-31T11:44:00.742311Z  2539       en      2.597      5  Positive   

     thumbsUpCount                   updated_at  
0                0  2024-03-31T06:58:47.318813Z  
1                0  2024-03-31T06:59:03.859527Z  
2                0  2024-03-31T06:59:46.583307Z  
3                0  2024-03-31T06:59:58.593889Z  
4                0  2024-03-31T07:00:26.848109Z  
..             ...                          ...  
383              0  2024-03-31T11:39:35.667327Z  
384              0  2024-03-31T11:39:43.659780Z  
385              0  2024-03-31T11:29:04.279018Z  
386              0  2024-03-31T11:40:03.224623Z  
387              0  2024-03-31T11:44:00.742662Z  

[388 rows x 12 columns]

In [12]:
final_df = df[['Financial_context','sentiment','content']]

In [13]:
final_df

Financial_context sentiment  \
0           Financial  Positive   
1       Non Financial   Neutral   
2       Non Financial   Neutral   
3       Non Financial  Positive   
4       Non Financial  Negative   
..                ...       ...   
383     Non Financial  Negative   
384         Financial  Negative   
385     Non Financial  Negative   
386         Financial  Negative   
387         Financial  Positive   

                                               content  
0                  1] Customer service is really nice.  
1    2] It is not very easy to set up mobile bankin...  
2     I understand it's for safety but still a hassle.  
3                        3] App itself is easy to use.  
4    4] Unfortunately, you can't view your card num...  
..                                                 ...  
383                I don't know what's is the problem?  
384                           It's very disappointing.  
385  2nd largest bank in India but mobile app is no...  
386                                       What a pity.  
387                                           Perfect!  

[388 rows x 3 columns]

In [33]:
from sklearn.model_selection import train_test_split
import pandas as pd

# Set aside a portion of the data for evaluation
eval_fraction = 0.1  # For example, 10% of the data for evaluation
train_test_data, X_eval_initial = train_test_split(final_df, test_size=eval_fraction, random_state=42)

X_train = []
X_test = []

# Iterate over each sentiment category
for sentiment in ["Positive", "Neutral", "Negative"]:
    # Filter data for the current sentiment
    subset = train_test_data[train_test_data['sentiment'] == sentiment]

    # Determine the sizes for the training and testing sets
    subset_size = len(subset)
    train_size = min(300, int(subset_size * 0.7))  # Aim for 70% of data for training, max 300
    test_size = min(100, subset_size - train_size)  # Remainder for testing, max 100

    # Split the subset into training and testing, ensuring there's data to split
    if subset_size > 0:
        train, test = train_test_split(subset,
                                       train_size=train_size,
                                       test_size=test_size,
                                       random_state=42)
        X_train.append(train)
        X_test.append(test)

# Concatenate the split subsets into full training and testing datasets
if X_train and X_test:
    X_train = pd.concat(X_train).sample(frac=1, random_state=10).reset_index(drop=True)
    X_test = pd.concat(X_test).reset_index(drop=True)
else:
    print("No data available for training and testing sets.")

# Use the initially set aside evaluation set
X_eval = X_eval_initial.reset_index(drop=True)

# Optionally, balance the evaluation set by sentiment
# This step should be carefully managed to avoid inflating the size of X_eval
X_eval = (X_eval
          .groupby('sentiment', group_keys=False)
          .apply(lambda x: x.sample(min(len(x), 50), random_state=10)))
X_eval = X_eval.reset_index(drop=True)

# Load Gemma-2b model

In [15]:
from huggingface_hub import notebook_login
notebook_login()

In [17]:
from transformers import (AutoModelForCausalLM,
                          AutoTokenizer,
                          BitsAndBytesConfig,
                          TrainingArguments,
                          pipeline,
                          logging)
import torch
compute_dtype = getattr(torch, "float16")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
)


model = AutoModelForCausalLM.from_pretrained(
   'google/gemma-2b',
    device_map="auto",
    quantization_config=bnb_config,
)

model.config.use_cache = False
model.config.pretraining_tp = 1

max_seq_length = 2048
tokenizer = AutoTokenizer.from_pretrained('google/gemma-2b', max_seq_length=max_seq_length)
EOS_TOKEN = tokenizer.eos_token

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/555 [00:00<?, ?B/s]

In [18]:
import bitsandbytes as bnb
def find_all_linear_names(model):
  cls = bnb.nn.Linear4bit #if args.bits == 4 else (bnb.nn.Linear8bitLt if args.bits == 8 else torch.nn.Linear)
  lora_module_names = set()
  for name, module in model.named_modules():
    if isinstance(module, cls):
      names = name.split('.')
      lora_module_names.add(names[0] if len(names) == 1 else names[-1])
    if 'lm_head' in lora_module_names: # needed for 16-bit
      lora_module_names.remove('lm_head')
  return list(lora_module_names)

In [19]:
modules = find_all_linear_names(model)
print(modules)

['gate_proj', 'k_proj', 'down_proj', 'o_proj', 'v_proj', 'up_proj', 'q_proj']


# Pre Processing Dataset

In [40]:
def generate_prompt(data_point):
    return f"""
            Analyze the sentiment of the statement enclosed in square brackets,
            determine if it is positive, neutral, or negative, and return the answer as
            the corresponding sentiment label "Positive", "Neutral", or "Negative".
            Also, predict whether the statement is Financial or Non-Financial.

           Statement = [{data_point['content']}]

           Sentiment = {data_point['sentiment']}

           Financial Status = {data_point['Financial_context']}

            """.strip() + EOS_TOKEN

In [41]:
def generate_test_prompt(data_point):
    return f"""
           Analyze the sentiment of the statement enclosed in square brackets,
            determine if it is positive, neutral, or negative, and return the answer as
            the corresponding sentiment label "Positive" or "Neutral" or "Negative"

         Statement = [{data_point['content']}]

          Sentiment = {data_point['sentiment']}

          Financial Status = {data_point['Financial_context']}

    """.strip()

In [42]:
X_train['prompt'] = X_train.apply(generate_prompt, axis=1)
X_test['prompt'] = X_test.apply(generate_test_prompt, axis=1)
X_eval['prompt'] = X_eval.apply(generate_prompt, axis=1)

In [43]:
y_true = X_test[['sentiment', 'Financial_context']]
y_true_sentiment = X_test['sentiment']
y_true_financial = X_test['Financial_context']

In [44]:
pd.DataFrame(X_train.apply(generate_prompt, axis=1), columns=["prompt"])

prompt
0    Analyze the sentiment of the statement enclose...
1    Analyze the sentiment of the statement enclose...
2    Analyze the sentiment of the statement enclose...
3    Analyze the sentiment of the statement enclose...
4    Analyze the sentiment of the statement enclose...
..                                                 ...
238  Analyze the sentiment of the statement enclose...
239  Analyze the sentiment of the statement enclose...
240  Analyze the sentiment of the statement enclose...
241  Analyze the sentiment of the statement enclose...
242  Analyze the sentiment of the statement enclose...

[243 rows x 1 columns]

In [45]:
from datasets import Dataset

train_data = Dataset.from_pandas(X_train[['prompt']])
eval_data = Dataset.from_pandas(X_eval[['prompt']])
test_data = Dataset.from_pandas(X_test[['prompt']])

In [49]:
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             confusion_matrix)
import numpy as np
def sent_evaluate(y_true, y_pred):
    labels = ['Positive', 'Neutral', 'Negative']
    mapping = {'Positive': 2, 'Neutral': 1,'none':1, 'Negative': 0}
    def map_func(x):
        return mapping.get(x, 1)

    y_true = np.vectorize(map_func)(y_true)
    y_pred = np.vectorize(map_func)(y_pred)

    # Calculate accuracy
    accuracy = accuracy_score(y_true=y_true, y_pred=y_pred)
    print(f'Accuracy: {accuracy:.3f}')

    # Generate accuracy report
    unique_labels = set(y_true)  # Get unique labels

    for label in unique_labels:
        label_indices = [i for i in range(len(y_true))
                         if y_true[i] == label]
        label_y_true = [y_true[i] for i in label_indices]
        label_y_pred = [y_pred[i] for i in label_indices]
        accuracy = accuracy_score(label_y_true, label_y_pred)
        print(f'Accuracy for label {label}: {accuracy:.3f}')

    # Generate classification report
    class_report = classification_report(y_true=y_true, y_pred=y_pred)
    print('\nClassification Report:')
    print(class_report)

    # Generate confusion matrix
    conf_matrix = confusion_matrix(y_true=y_true, y_pred=y_pred, labels=[0, 1, 2])
    print('\nConfusion Matrix:')
    print(conf_matrix)

In [57]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def evaluate(y_true_sentiment, y_pred_sentiment, y_true_financial, y_pred_financial):
    # Evaluation for sentiment
    sentiment_labels =  ['Positive', 'Neutral', 'Negative']
    sentiment_mapping = {'Positive': 2, 'Neutral': 1,'none':1, 'Negative': 0}

    y_true_sentiment_mapped = np.vectorize(sentiment_mapping.get)(y_true_sentiment)
    y_pred_sentiment_mapped = np.vectorize(sentiment_mapping.get)(y_pred_sentiment)

    print("Sentiment Analysis")
    print("------------------")
    print('Accuracy:', accuracy_score(y_true_sentiment_mapped, y_pred_sentiment_mapped))
    print('\nClassification Report:')
    print(classification_report(y_true_sentiment_mapped, y_pred_sentiment_mapped, target_names=sentiment_labels))
    print('Confusion Matrix:')
    print(confusion_matrix(y_true_sentiment_mapped, y_pred_sentiment_mapped, labels=[2, 1, 0]))

    # Evaluation for financial status
    financial_labels = ['Financial', 'Non Financial']
    financial_mapping = {'Financial': 1, 'Non Financial': 0 , 'none': 0}

    y_true_financial_mapped = np.vectorize(financial_mapping.get)(y_true_financial)
    y_pred_financial_mapped = np.vectorize(financial_mapping.get)(y_pred_financial)

    print("\nFinancial Status Analysis")
    print("-------------------------")
    print('Accuracy:', accuracy_score(y_true_financial_mapped, y_pred_financial_mapped))
    print('\nClassification Report:')
    print(classification_report(y_true_financial_mapped, y_pred_financial_mapped, target_names=financial_labels))
    print('Confusion Matrix:')
    print(confusion_matrix(y_true_financial_mapped, y_pred_financial_mapped, labels=[1, 0]))

In [51]:
from tqdm import tqdm

def predict(X_test, model, tokenizer):
    y_pred_sentiment = []
    y_pred_financial = []
    for i in tqdm(range(len(X_test))):
        prompt = X_test.iloc[i]["prompt"]
        input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")
        outputs = model.generate(**input_ids, pad_token_id=tokenizer.eos_token_id, max_new_tokens=1, temperature=0.0)
        result = tokenizer.decode(outputs[0])

        # Sentiment analysis
        sentiment = "none"  # Default sentiment
        parts = result.split("Sentiment =")
        if len(parts) > 1:
            sentiment_part = parts[1].split("\n")[0].strip()
            if "positive" in sentiment_part.lower():
                sentiment = "Positive"
            elif "negative" in sentiment_part.lower():
                sentiment = "Negative"
            elif "neutral" in sentiment_part.lower():
                sentiment = "Neutral"
        y_pred_sentiment.append(sentiment)

        # Extract financial status
        financial = "none"
        financial_parts = result.split("Financial Status = ")
        if len(financial_parts) > 1:
            financial_part = financial_parts[1].split("\n")[0].strip()
            if "non financial" in financial_part.lower():
                financial = "Non Financial"
            elif "financial" in financial_part.lower():
                financial = "Financial"
        y_pred_financial.append(financial)

    return y_pred_sentiment, y_pred_financial

In [52]:
y_pred_sentiment,y_pred_financial =predict(X_test, model, tokenizer)

  0%|          | 0/106 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
100%|██████████| 106/106 [00:12<00:00,  8.34it/s]


In [55]:
sent_evaluate(y_true_sentiment, y_pred_sentiment)

Accuracy: 1.000
Accuracy for label 0: 1.000
Accuracy for label 1: 1.000
Accuracy for label 2: 1.000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        52

    accuracy                           1.00       106
   macro avg       1.00      1.00      1.00       106
weighted avg       1.00      1.00      1.00       106


Confusion Matrix:
[[45  0  0]
 [ 0  9  0]
 [ 0  0 52]]


In [58]:
evaluate(y_true_sentiment, y_pred_sentiment, y_true_financial, y_pred_financial)

Sentiment Analysis
------------------
Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

    Positive       1.00      1.00      1.00        45
     Neutral       1.00      1.00      1.00         9
    Negative       1.00      1.00      1.00        52

    accuracy                           1.00       106
   macro avg       1.00      1.00      1.00       106
weighted avg       1.00      1.00      1.00       106

Confusion Matrix:
[[52  0  0]
 [ 0  9  0]
 [ 0  0 45]]

Financial Status Analysis
-------------------------
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

    Financial       1.00      1.00      1.00        43
Non Financial       1.00      1.00      1.00        63

     accuracy                           1.00       106
    macro avg       1.00      1.00      1.00       106
 weighted avg       1.00      1.00      1.00       106

Confusion Matrix:
[[63  0]
 [ 0 43]]
